'use client'
//import { Comfortaa  } from 'next/font/google'
import {Poppins  } from 'next/font/google'

const inter = Poppins  ({ subsets: ['latin'] ,weight: '400',})
import { CacheProvider } from "@chakra-ui/next-js"
import { ChakraProvider,extendTheme } from "@chakra-ui/react"
import Navbar from './components/Navbar'
export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}
const theme = extendTheme({
  styles: {
    global: {
      body: {
       bg:"gray.300",
       color:'gray.800'
      },
    },
  },
 
});
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <CacheProvider>
        <ChakraProvider theme={theme}>
          <Navbar/>
        {children}
        </ChakraProvider>
        </CacheProvider>
      </body>
    </html>
  )
}
